### ISSUE TITLE
Potential ambiguities in 4.4 and 4.5

### ISSUE THREAD

**Issue by lminiero** [AOMediaCodec/av1-rtp-spec#106]
Hi,

I've recently started playing with the libwebrtc-AV1 implementation made available by CoSMo, so I started studying the RTP specification as well in order to be able to depacketize the payload. I encountered a couple of potential ambiguities, though.

The first one is in section 4.4, where the `W` field is introduced:

> W: two bit field that describes the number of OBU elements in the packet. This field MUST be set equal to 0 or equal to the number of OBU elements contained in the packet. If set to 0, each OBU element MUST be preceded by a length field. If not set to 0 the last OBU element MUST NOT be preceded by a length field.

The ambiguity is in what to do when `W=1`. In that case, you only have a single OBU in the packet, which means that it's, by definition, also the last element. It's not clear if in that case the leb128 length field is still required, or if it's missing and the following formula should be used to calculate the length as well. The text seems to suggest the latter (no length field if W=1), but it's not 100% clear (I have to admit I'm not sure what the libwebrtc-AV1 implementation does, for instance, since my RTP depacketizer still doesn't fully work).

Which brings me to the second ambiguity. In the 4.5 figure, the OBU element size covers two bytes, but leb128 can actually span over more or less, depending on whether the MSB is 1 or not. I guess the rationale is that an RTP packet size will always fit in two bytes max, but a small size could fit in a single byte, with its MSB=0. Within the context of the RTP packetization, are we supposed to assume that the length field will ALWAYS be two bytes, even if the actual leb128 field only requires one? (in which case we just skip the second byte?)

Thanks for the clarifications.

**Comment by aboba** [comment]
For W=1, there is no length field. The leb128 field is dynamic, so it won't always be 2 bytes.

**Comment by lminiero** [comment]
Thanks for the clarification @aboba: in the meanwhile I managed to get my parser working, so I can confirm that's how libwebrtc is doing things too, and how I ended up processing the packets. It might still make sense to make this clearer in the specification, just in case I'm not the only one confused :-)
