### ISSUE TITLE
Testing coverage - adding flags to the HTML spec

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#115]
short:
the w3c webrtc group has done the background work to automatically recognise sections of the document, automatically mark the normative one, and automatically link to existing tests. However, the tags they use to delimit sections are not used in the current AV1 doc. This ticket is here to discuss the best approach to add those tags in. Bernard is likely the most knowledgeable here, having used and edited both docs.

--------------
long:

The AV1 RTP Payload spec is written in **markdown**.
Source file: av1-rtp-spec.md
https://github.com/AOMediaCodec/av1-rtp-spec

The process to convert it to HTML makes use of **Jekyll**:
https://jekyllrb.com/

**Jekyll** is written in Ruby and makes use of the **kramdown** package to parse the 
input file in **markdown** and generate HTML.

The resulting AV1 RTP Payload spec in HTML:
https://aomediacodec.github.io/av1-rtp-spec/

In this HTML file, titles are identified by header tags
and each paragraph is enclosed in paragraph tags.

For W3C **respec**, the input file is also in HTML, titles are also 
identified by header. tags
and each paragraph is also enclosed in paragraph tags.

However, **respec** makes use of an additional tag: <section>...</section>
Titles and paragraphs are enclosed inside a <section>.
There are some special sections that must exist in the HTML document:
<section id='abstract'> ... </section>
<section id='sotd'> ... <section>
<section id='conformance'> ... </section>

Sections can be nested. respec use the <section> tags for numbering each 
section, subsection, subsubsection..., as a base to the algorithm which decides which section are normative and which are not, and as a base for the colouring scope.

There is no section tags in the AV1 RTP Payload spec.

Then there are the **data-tests** attributes that are added to either p or 
li tags. The data-tests attributes give a list of tests relative to 
the paragraph:
<p data-tests="test1.html, test2.html">
    Text of the paragraph...
</p>

The main problem for AV1 RTP Payload seems to convert the source 
markdown file av1-rtp-spec.md into HTML that would be compatible with 
respec HTML format (with section tags).
Ruby parser kramdown does not do it.

- do we extend kramdown (does not feel right)
- do we extend Jekyll ?
- do we embrace ref specs?
- do we do an extra pass after the html has been generated, at the cost of maintaining the annotations outside of the markdown?

**Comment by StephenBotzko** [comment]
We will handle test coverage in its own document ( https://cosmosoftware.github.io/av1-rtp-spec-html/ ).
