### ISSUE TITLE
Normative use of "COULD"?

### ISSUE THREAD

**Issue by StephenBotzko** [AOMediaCodec/av1-rtp-spec#130]
COULD appears to be used normatively in 7.2.1 and 7.2.3, but is not identified as a normative keyword in section 2 (or RFC2119).

These sections should be changed to either "MAY" or "SHOULD" - it isn't clear which term was meant.

**Comment by aboba** [comment]
Based on the context, it looks like "MAY" could be substituted for "COULD".
