### ISSUE TITLE
Use of AV1 hyperlink isn't consistent

### ISSUE THREAD

**Issue by StephenBotzko** [AOMediaCodec/av1-rtp-spec#133]
In many cases, AV1 is a hyperlink to the AV1 Bitstream & Decoding process.  However, this is not always done, and there is no apparent rule being applied on when it should be a hyperlink.

Also, the specification is refered to using various names - "AV1 bitstream specification", "AV1 Specification", "video codec", "AV1 video codec specfication", and "AV1 bitstream format"  Ideally there would be only title used for the specification.

BTW, the title is misspelled in both 11.1 and A.7.2

**Comment by aboba** [comment]
Spelling mistakes ("bistream") have been fixed and many of the links have been removed.  Please review the latest version of the specification to clarify what else needs to be done.

**Comment by StephenBotzko** [comment]
Addressed in Pull Request #138
