### ISSUE TITLE
Security Section

### ISSUE THREAD

**Issue by StephenBotzko** [AOMediaCodec/av1-rtp-spec#134]
While this text appears in various forms for other video codecs, it is rather confusing, and perhaps should be simplified.

"Decoders MUST exercise caution with respect to the handling of reserved OBU types and reserved metadata OBU types, particularly if they contain active elements, and MUST restrict their domain of applicability to the presentation containing the stream. The safest way is to simply discard these OBUs."

This appears to be applied to handling of currently unspecified OBU types and metadata types.  Those should be discarded in any event, since they cannot be parsed.

If it applies to specified OBUs, then it isn't clear that "active elements" means.  So perhaps just eliminate that clause, but keep the normative MUST?

**Comment by StephenBotzko** [comment]
Maybe add some text saying that middleboxes shouldn't attempt to parse OBUs they can't understand., and don't need to parse OBUs if they are using the dependency descriptors.

Also maybe that the temporal delimiter and the tile list OBU should be filtered out if it is carried in the RTP payload???

**Comment by aboba** [comment]
Closing as a result of merging the PR.
