### ISSUE TITLE
More higher level description in Section A.1?

### ISSUE THREAD

**Issue by StephenBotzko** [AOMediaCodec/av1-rtp-spec#135]
The concept of chains is key to the appendix, and should be introduced in the introduction (A.1).  A diagram showing how everything fits together would be helpful.  Perhaps one of the tables in the examples could be useful starting point?

**Comment by aboba** [comment]
Good point. Chains is one of the concepts that people often have trouble grasping.

**Comment by StephenBotzko** [comment]
Addressed in Pull Request #140
