### ISSUE TITLE
Add OBU header to to section 2. Conventions, Definitions and Acronyms

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#156]
OBU headers are referenced several times in the draft, but there is no way to know that you have to look at the av1 spec to understand what they refer to.

**Comment by mhoro** [comment]
There is one instance of the phrase "OBU header" in the draft AV1 RTP specification, so I'm hesitant to add a definition to Section 2. Rather, adding a description for OBU header would be preferable. Further, given that "OBU header" occurs in the same sentence as a reference to the AV1 specification where OBU header is clearly defined, I am inclined to leave the current AV1 RTP draft unchanged.

**Comment by StephenBotzko** [comment]
We believe the current specification is  clear enough, so we will not address this feedback.
