### ISSUE TITLE
[question] Is the dependency structure present in all rtp packets?

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#159]
The spec seems to state that the DD must be included in every RTP packet, however shouldn't it be enough to send it once per aggregated OBUS belonging to same temporal/spatial layers?

In any case, even if the DD is present in every packet, the SFM will need to read the aggregation header information to determine if a missing packet belongs to current frame or not.

Furthermore, is it possible to send OBUS of same spatial and temporal layer in different aggregations? I can't find were it is explicitly forbidden (not sure if the encoder would even produce them).

**Comment by DanilChapovalov** [comment]
yes, DD must be included in every RTP packet.

flags in the aggregation header describe OBU boundaries, not rtp frame boundaries, in particular it is possible to send two rtp packets, each containing a single OBU, but that two OBUs forming a single rtp frame.

there shouldn't be need to read aggregation header to find all rtp packet for a frame. DD has start_of_frame, end_of_frame flags and frame_number to detect in SFM when a packet or missing packet belongs to a frame.

There is a phrase "An RTP frame contains one complete coded video frame and may also contain additional information (e.g., metadata).".
Afaik it is not allowed by the main AV1 spec to have two different coded video frames with the same spatial id from the same temporal unit, but if for any reason it is allowed, then DD allows to send those in two different rtp frame aggregations.

**Comment by murillo128** [comment]
My bad, too tired. I was digging into the templates/diffs structs and I overlooked the obvious start/end frame bits of the DD.
