### ISSUE TITLE
NOT TESTABLE: 6.1 Simulcast paragraph 1

### ISSUE THREAD

**Issue by ludocosmo** [AOMediaCodec/av1-rtp-spec#183]
The RTP payload defined in this specification supports two distinct modes for transport of simulcast encodings. In either mode, simulcast transport MUST only be used to convey multiple encodings from the same source. Also, in either mode, a sequence header OBU SHOULD be aggregated with each spatial layer. Both modes MUST be supported by implementations of this specification.

**Comment by aboba** [comment]
Can't we test whether the sequence header OBU is aggregated with each spatial layer? Also, can't we test whether an implementation supports both "S" mode and distinct SSRC simulcast?

**Comment by StephenBotzko** [comment]
The second sentence can only be tested by analyzing the decoded video, and is outside of scope.  The third sentence is testable.  The last sentence is testable.

**Comment by agouaillard-cosmo** [comment]
Spreadsheet updated accordingly. Annotated document to be annotated. Can be closed.
