### ISSUE TITLE
NOT TESTABLE: 6.1 Simulcast paragraph 2

### ISSUE THREAD

**Issue by ludocosmo** [AOMediaCodec/av1-rtp-spec#184]
When simulcast encodings are transported each on a separate RTP stream, each simulcast encoding utilizes a distinct bitstream containing its own distinct Sequence Header and Scalability Metadata OBUs. This mode utilizes distinct SSRCs and Restriction Identifiers (RIDs) for each encoding as described in [I-D.ietf-avtext-rid] and, as a result, RTCP feedback can be provided for each simulcast encoding. This mode of simulcast transport, which MUST be supported by SFMs, utilizes Session Description Protocol (SDP) signaling as described in [I-D.ietf-mmusic-sdp-simulcast] and [I-D.ietf-mmusic-rid].

**Comment by aboba** [comment]
Isn't it possible to test whether a simulcast bitstream includes Sequence Header and Scalability Metadata OBUs?  Also, can't we test whether distinct SSRCs and RIDs are used?

**Comment by StephenBotzko** [comment]
The only normative text is the last sentence, which can be tested.

**Comment by agouaillard-cosmo** [comment]
Spreadsheet has been updated, and annotated document is in progress. can be closed.
