### ISSUE TITLE
NOT TESTABLE: 8.1 Full Intra Request (FIR) paragraph 3

### ISSUE THREAD

**Issue by ludocosmo** [AOMediaCodec/av1-rtp-spec#185]
If simulcast encodings of the same source are transported on distinct SSRCs,
then in addition to sending a new coded video sequence for each encoding
corresponding to an SSRC in the FIR message, the AV1 sender MAY also send
new coded video sequences for other encodings from the same source(s).

**Comment by aboba** [comment]
This seems like it should be testable.  If a FIR is sent to an implementation sending simulcast, then a new coded video sequence should be received for each encoding.

**Comment by StephenBotzko** [comment]
I agree it is testable, but it probably doesn't need to be tested.

**Comment by agouaillard-cosmo** [comment]
Spreadsheet updated and annotated document being updated. Can be closed.
