### ISSUE TITLE
NOT TESTABLE: 10 Security Considerations paragraph 3

### ISSUE THREAD

**Issue by ludocosmo** [AOMediaCodec/av1-rtp-spec#186]
Decoders MUST discard reserved OBU types and reserved metadata OBU types, and SHOULD filter out temporal delimiter and tile list OBUs carried within the RTP payload. Middle boxes SHOULD NOT parse OBUs they do not support. SFMs MUST NOT parse OBUs at all, but instead MUST make forwarding decisions based on the information within the RTP header and Dependency Descriptor RTP header extension.

**Comment by aboba** [comment]
Isn't this testable?  Send a reserved OBU type or reserved metadata OBU type to the implementation and see what happens.  Also, you can send an unsupported OBU to an SFM and see whether it can handle it.  Also, if the payload is E2E encrypted, you can test whether the SFM makes forwarding decisions based on only the RTP header and DD.

**Comment by StephenBotzko** [comment]
Decoder operation here won't be tested, but is normative.  The middle box sentence is not externally testable.

The third sentence can be removed, as it is really the definition of an SFM.

**Comment by StephenBotzko** [comment]
Closed in PR #192
