### ISSUE TITLE
NOT TESTABLE: 10 Security Considerations paragraph 4

### ISSUE THREAD

**Issue by ludocosmo** [AOMediaCodec/av1-rtp-spec#187]
When integrity protection is applied to a stream, care MUST be taken that the stream being transported may be scalable; hence a receiver may be able to access only part of the entire stream.

**Comment by StephenBotzko** [comment]
We'll remove this paragraph.

**Comment by agouaillard-cosmo** [comment]
#192 removes that text. Can close.
