### ISSUE TITLE
Clarify what is the validity of the active_decode_targets_bitmask 

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/av1-rtp-spec#190]
Currently we have this regarding the active decode targe mask:

>on SFM may change which Decode targets it forwards. Similarly, a sender may change the Decode targets that are currently being produced. In both cases, not all Decode targets may be available for decoding. Such changes SHOULD be signaled to the receiver using the active_decode_targets_bitmask and SHOULD be signaled to the receiver in a reliable way.

> When not all Decode targets are active, the active_decode_targets_bitmask MUST be sent in every packet where the template_dependency_structure_present_flag is equal to 1.

> Note: One way to achieve reliable delivery is to include the active_decode_targets_bitmask in every packet until a receiver report acknowledges a packet containing the latest active_decode_targets_bitmask. Alternately, for many video streams, reliable delivery may be achieved by including the active_decode_targets_bitmask on every chain in the first packet after a change in active decode targets.

But we have not specified anywhere when the absence of the `active_decode_targets_bitmask`  overrides previous sent one.

If  `template_dependency_structure_present_flag==1` I would say that the active decode targets overrides previous ones regardless ìf the `active_decode_targets_bitmask`. That is, if  `active_decode_targets_present_flag` equals 1, then obviously the mask is the one sent in the packet, and if not, all the decode targets are sent .

What happens if `template_dependency_structure_present_flag==0`? If `active_decode_targets_present_flag==0`, I would say that the latest received mask is in use, is that right? 

 If `active_decode_targets_present_flag==1` instead, does the mask applies only for the current packet? or also for subsequent packets?

**Comment by StephenBotzko** [comment]
We need clarifying text for this.

**Comment by agouaillard** [comment]
status update from sergio: "Waiting for google for providing the PR to address it"

**Comment by StephenBotzko** [comment]
Addressed in PR #213
