### ISSUE TITLE
Testable? To be tested? 6 MANE and SFM Behavior | 1

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#196]
If a packet contains an OBU with an OBU extension header then the entire packet is considered associated with the layer identified by the temporal_id and spatial_id combination that are indicated in the extension header. If a packet does not contain any OBU with an OBU extension header, then it is considered to be associated with all operating points.

For discussion.

**Comment by StephenBotzko** [comment]
As written this paragraph is not normative.  But there are normative implications on forwarding packets that are "associated with all operating points".

**Comment by aboba** [comment]
Yes. This could be tested by sending a packet without any OBU with an OBU extension header, and seeing if it is forwarded by the SFU.

**Comment by StephenBotzko** [comment]
The text isn't normative, it is descriptive/definitional.
