### ISSUE TITLE
8.2 Layer Refresh Request (LRR) | 2 and 3

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#198]
AV1 streams MUST use the Layer Refresh Request format defined for VP9 in Section 5.3 of I-D.ietf-payload-vp9, with the high order bit of its three-bit SID field set to 0. Figure 4 shows the format for AV1 streams. Notice that SID here is two bits. SID is associated with AV1’s spatial_id and TID is associated with AV1’s temporal_id. See Sections 2, 5.3.3, and 6.2.3 of the AV1 bitstream specification AV1 for details on the temporal_id and spatial_id fields.

Identification of a layer refresh frame may be performed by examining the coding dependency structure of the coded video sequence it belongs to. This may be provided by the scalability metadata (Sections 5.8.5 and 6.7.5 of AV1), either in the form of a pre-defined scalability mode or through a scalability structure (Sections 5.8.6 and 6.7.6 of AV1). Alternatively, the Dependency Descriptor RTP header extension that is specified in Appendix A of this document may be used.

Suggested: testable but not to be tested as there is no implementation in libwebrtc today.

**Comment by agouaillard-cosmo** [comment]
proposal: evaluate the effort, as there is interest in implementing it anyway. To revisit on Nov. 16th

**Comment by StephenBotzko** [comment]
Resolved as testable, but cannot be tested w/o a libwebrtc implemenation of LRR.
