### ISSUE TITLE
A.6: Is Normative?

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#202]
section A.6 Dependency Descriptor Format,
paragraph 2
spatial ID
temporal ID
DTIsframe_number of the current frameframe_number of each of the Referred framesframe_number of last frame in each Chain

Sergio: non normative

**Comment by StephenBotzko** [comment]
The main body of A.6 is an introduction to the normative sections, and it is not itself normative.

**Comment by agouaillard-cosmo** [comment]
Reference testing document updated accordingly.
