### ISSUE TITLE
Media Type Definition is not implemented in libwebrtc.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#206]
Those are not implemented in libwebrtc as far as we can tell. Either it gets implemented or it is not testable as-is. Note: this is for receiver capacity negotiation, and might not be critical at first. It impacts other sections though, for which a separate ticket will be open and dependency on this one explicitly mentioned.

7.1 Media Type Definition | 8 | Optional parameters: These parameters are used to signal the capabilities of a receiver implementation. If the implementation is willing to receive media, profile and level-idx parameters MUST be provided. These parameters MUST NOT be used for any other purpose.

7.1 Media Type Definition | 9 | profile: The value of profile is an integer indicating the highest AV1 profile supported by the receiver. The range of possible values is identical to the seq_profile syntax element specified in AV1

7.1 Media Type Definition | 10 | level-idx: The value of level-idx is an integer indicating the highest AV1 level supported by the receiver. The range of possible values is identical to the seq_level_idx syntax element specified in AV1

7.1 Media Type Definition | 11 | tier: The value of tier is an integer indicating tier of the indicated level. The range of possible values is identical to the seq_tier syntax element specified in AV1. If parameter is not present, level’s tier is to be assumed equal to 0

**Comment by aboba** [comment]
This sounds more like a bug to be filed in the Chromium or webrtc.org bug repo than an AV1 RTP payload specification bug.

**Comment by agouaillard-cosmo** [comment]
Minimum mechanism with a unique profile and level, the one currently implemented, could and should be supported. However it is unlikely that we would test all the possible combinations. Test could be added later on as new profiles would become available.

**Comment by StephenBotzko** [comment]
A test patch for webrtc was created which allowed this negotiation to be tested.
