### ISSUE TITLE
Mapping of the media type parameters to SDP is impossible without media type support.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#207]
see #206 

7.2.1 Mapping of Media Subtype Parameters to SDP | 5 | The parameters “profile”, and “level-idx”, MUST be included in the “a=fmtp” line of SDP if SDP is used to declare receiver capabilities. These parameters are expressed as a media subtype string, in the form of a semicolon separated list of parameter=value pairs.

**Comment by aboba** [comment]
This sounds more like a bug to be filed in the Chromium or webrtc.org bug repo than an AV1 RTP payload specification bug.

**Comment by agouaillard-cosmo** [comment]
see #206 for discussion

**Comment by StephenBotzko** [comment]
A test patch for webrtc was created which allowed this negotiation to be tested.
