### ISSUE TITLE
Media types cannot be supported in SDP signalling if they are not supported in libwebrtc itself.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#208]
see #206 

7.2.3 Usage with the SDP Offer/Answer Model | 2 | The media format configuration is identified by level-idx, profile and tier. The answerer SHOULD maintain all parameters. These media configuration parameters are asymmetrical and the answerer MAY declare its own media configuration if the answerer capabilities are different from the offerer.

7.2.3 Usage with the SDP Offer/Answer Model | 3 | The profile to use in the offerer-to-answerer direction MUST be lesser or equal to the profile the answerer supports for receiving, and the profile to use in the answerer-to-offerer direction MUST be lesser or equal to the profile the offerer supports for receiving.

7.2.3 Usage with the SDP Offer/Answer Model | 4 | The level to use in the offerer-to-answerer direction MUST be lesser or equal to the level the answerer supports for receiving, and the level to use in the answerer-to-offerer direction MUST be lesser or equal to the level the offerer supports for receiving.

7.2.3 Usage with the SDP Offer/Answer Model | 5 | The tier to use in the offerer-to-answerer direction MUST be lesser or equal to the tier the answerer supports for receiving, and the tier to use in the answerer-to-offerer direction MUST be lesser or equal to the tier the offerer supports for receiving.

**Comment by aboba** [comment]
This sounds more like a bug to be filed in the Chromium or webrtc.org bug repo than an AV1 RTP payload specification bug.

**Comment by agouaillard-cosmo** [comment]
see #206 for discussion.

**Comment by StephenBotzko** [comment]
A test patch for webrtc was created which allowed this negotiation to be tested.
