### ISSUE TITLE
RID restrictions are not implemented in libwebrtc

### ISSUE THREAD

**Issue by agouaillard-cosmo** [AOMediaCodec/av1-rtp-spec#209]
The mapping and dependence toward #206 is also not clear.

7.2.2 RID Restrictions Mapping for AV1 | 2 | max-width, maximum width of the frame in units of samples. The meaning of the restriction is the same as variable MaxHSize of the levels table from Section A.3 of AV1.

7.2.2 RID Restrictions Mapping for AV1 | 3 | max-height, maximum height of the frame in units of samples. The meaning of the restriction is the same as variable MaxVSize of the levels table from Section A.3 of AV1.

7.2.2 RID Restrictions Mapping for AV1 | 4 | max-fps, maximum number of temporal units per second.

7.2.2 RID Restrictions Mapping for AV1 | 5 | max-fs, maximum size of the frame in units of samples. The meaning of the restriction is the same as variable MaxPicSize of the levels table from Section A.3 of AV1.

7.2.2 RID Restrictions Mapping for AV1 | 6 | max-br, maximum bit rate in units bits per second. The meaning of the restriction is the same as variable MaxBitrate defined in Section A.3 of AV1.

7.2.2 RID Restrictions Mapping for AV1 | 7 | max-pps, maximum decode rate in units of samples per second. The meaning of the restriction is the same as variable MaxDecodeRate of the levels table from Section A.3 of AV1.

7.2.2 RID Restrictions Mapping for AV1 | 8 | max-bpp, maximum number of bits per pixel of any given coded frame, calculated as a ratio between CompressedSize variable defined Section A.3 of AV1 and expressed in bits, and number of samples in frame.

7.2.2 RID Restrictions Mapping for AV1 | 9 | If during the SDP negotiation process both parties acknowledge restrictions, then the transported media stream MUST have at least one operating point with the negotiated restrictions.

**Comment by aboba** [comment]
RID restrictions are not supported in libwebrtc.  For the most part, they aren't needed because of the scaleResolutionDownBy, maxBitrate and maxFramerate.

**Comment by agouaillard-cosmo** [comment]
https://www.w3.org/TR/webrtc/#simulcast-functionality

"As defined in [JSEP] (section 3.7.), an offer from a user-agent will only contain a "send" description and no "recv" description on the a=simulcast line. Alternatives and **restrictions** (described in [MMUSIC-SIMULCAST]) are not supported."

**Comment by agouaillard-cosmo** [comment]
moved to the excellent sheet, part of the package for the codec group
