### ISSUE TITLE
AoM Email Address for receiving spec comments/issues?

### ISSUE THREAD

**Issue by StephenBotzko** [AOMediaCodec/av1-rtp-spec#227]
It would be good if there was an email address dedicated to getting feedback on AOM specifications.  That email address (if agreed to) should be included in the specification.

**Comment by aboba** [comment]
YEs, that does sound like a good idea.  Of course, the email address has to be monitored (e.g. forwarded to the chairs).

**Comment by agrange** [comment]
Other AoM specs on http://aomedia.org/ go directly to the relevant github.
