### ISSUE TITLE
clarification re Dependency Descriptor

### ISSUE THREAD

**Issue by zhuker** [AOMediaCodec/av1-rtp-spec#229]
> 4.3 Dependency Descriptor RTP Header Extension
> To facilitate the work of selectively forwarding portions of a scalable video bitstream, as is done by a Selective Forwarding Middlebox (SFM), certain information needs to be provided for each packet. Appendix A of this specification defines how this information is communicated.

Can the DD extension be omitted in absence of SFM or scalable video?
If so do you think it should be clarified?

**Comment by murillo128** [comment]
This is the actual behaviour of chrome implementation AFAIK. DD is only used when scalability modes are configured and not sent when scalability is not used.

Also, being a header extension and it has to be negotiated on the SDP by both endpoints, so any of them could decide to not enable it.

Not sure if it requires a modification on the draft though as the usage of the DD is not mandatory by the spec even in case that a SFM is in use.

**Comment by zhuker** [comment]
Thanks for the clarification
Shouldn't it say what you just said?

**Comment by aboba** [comment]
RTP header extensions (including negotiation) are defined in [RFC 8285](https://www.rfc-editor.org/rfc/rfc8285), which is cited as a normative reference. So there is no need to repeat text from RFC 8285 in this specification.
