### ISSUE TITLE
SDP parameters are needed for high bit depth flags

### ISSUE THREAD

**Issue by nirbheek** [AOMediaCodec/av1-rtp-spec#233]
The SDP parameter `profile` (AV1 `seq_profile`) is not sufficient to deduce which bit depth is supported by a peer, from page 32 of the spec:

```
high_bitdepth
if ( seq_profile == 2 && high_bitdepth ) {
  twelve_bit
  BitDepth = twelve_bit ? 12 : 10
} else if ( seq_profile <= 2 ) {
  BitDepth = high_bitdepth ? 10 : 8
}
```

So we need another parameter to signify 8-bit, 10-bit, 12-bit, with room reserved for a possible future 16-bit variant.

This will be a problem very soon, because Chrome only ships with dav1d in 8-bit mode, but services that use WHIP will want 10-bit support for ingest. Mobile apps such as [Facebook](https://engineering.fb.com/2023/02/21/video-engineering/av1-codec-facebook-instagram-reels/) have already deployed a combined 8-bit + 10-bit dav1d for reels and live streams, and WHIP ingest for live streaming is a real use-case.

**Comment by aboba** [comment]
Section A.2 of the AV1 spec requires main and high compliant decoders to decode both 8 and 10 bit streams.  Therefore, the desired signaling would only be relevant to a constrained (non-compliant) implementation.

**Comment by nirbheek** [comment]
Thanks! Good to know that lack of 10-bit support is a non-compliance issue in Chrome.

I think SDP parameters would still be needed for 12-bit?

**Comment by agrange** [comment]
The bitdepth cannot be determined from profile alone, as you say, but it is not necessary to determine bitdepth as part of the negotiation. If the underlying question is whether my decoder can decode the stream it is about to receive, then profile is sufficient, *if* the decoder is conformant to the AV1 specification. If the question is whether the bitdepth can be determined from the profile then the answer is 'no'.
