### ISSUE TITLE
Review of AV1 RTP Payload Specification: Are any changes needed?

### ISSUE THREAD

**Issue by aboba** [AOMediaCodec/av1-rtp-spec#238]
On April 8, 2024 the AV1 CODEC WG met to review potential updates to the AV1 specification.  The slides discussed are here:
[AV1_Layer-specific_OBUs_2024-04-08.pdf](https://github.com/AOMediaCodec/av1-rtp-spec/files/14911681/AV1_Layer-specific_OBUs_2024-04-08.pdf)

To retain backward compatibility, slide 15 makes the following recommendation:  
"New decoders should not enforce the new requirements on obu_extension_flag."

This raised the question: "If the new requirements cannot be enforced, why change the spec at all?" 

If the proposed changes are not made, are any changes needed to the AV1 RTP payload specification?

In my first pass review, there didn't seem to be any aspect of the AV1 RTP Payload specification that explicitly depends on the proposed bitstream changes. Rather, there are statements relating to layerIDs within an RTP payload that would apply to any RTP payload specification supporting scalability (e.g. prohibitions against mixing of layers).

**Comment by aboba** [comment]
@eleft @DanilChapovalov @Philipel-WebRTC PTAL.

**Comment by DanilChapovalov** [comment]
The way I read the change https://github.com/AOMediaCodec/av1-spec/pull/280/files  it consists of two parts:
1) replace "spatial level IDs > 0" with " obu_extension_flag = 1"
My understanding of this change is to make it technically correct: when obu_extension_flag equal to 0, then spatial id is not defined. That part feels like clarification, doesn't change how bitstream may be structured.

2) replace "increasing order" with "non-decreasing order" - that allows to have multiple OBUs with the same spatial_id per temporal unit, e.g. that allows to encode frame with spatial_id=1 not with an OBU_FRAME, but with OBU_FRAME_HEADER and multiple OBU_TILE_GROUP. That part seems to be not backward compatible.

the linked slide claims that
"new decoders Should allow layer-specific OBUs of the base layer to have
obu_extension_flag equal to 0 when scalability is being used"

That part seems to contradict unchanged rule in the same AV1 main spec "7.5. ordering of OBUs" section:
"If a coded video sequence contains at least one enhancement layer ... then all frame headers and tile group OBUs ... must include the OBU extension header."

I've also reread the RTP spec, specially section 5 Packetization Rules that feels most relevant to this AV1 spec change, but I haven't found anything that needs changing.
(e.g. statement "If more than one OBU contained in an RTP packet has an OBU extension header, then the values of the temporal_id and spatial_id MUST be the same in all such OBUs in the RTP packet." explicitly precondition requirements for spatial_id on presence of the OBU extension header, puts no requirement when spatial id is not defined. )

**Comment by DanilChapovalov** [comment]
I've checked the motivation for the change (as described in https://github.com/AOMediaCodec/av1-spec/pull/280)
Current AV1 spec wording allows frame with spatial_id=1 to be before frame with spatial_id=0.

In the RTP spec I think we implicitly rely on frames in the same temporal unit to be in spatial id order. So if AV1 spec changes are not approved, we might want to restrict RTP spec to only handle bitstream where frames in same temporal unit are ordered by spatial id.
e.g. it might be surprising to set marker bit on last frame with spatial_id=0 when there was also a frame with spatial_id=1.

If " new requirements on obu_extension_flag" are not enforced, then sequence header OBU may have extension, and RTP spec might then need different wording to describe how to handle it, e.g. should specify that OBU extension header should be removed for the SH by the sender and ignored by the receiver.

**Comment by mhoro** [comment]
Danil, Thank you for reviewing the RTP spec and for reporting your findings.

Everyone, I'd like to float the idea of removing the publication of the AV1
spec update as a dependency on the publication of the RTP for AV1
specification. To that end, I propose that we wait a few weeks for further
comments and update the RTP for AV1 text to address the reported
issues/comments.

     -michael

**Comment by aboba** [comment]
FYI, there will be another AV1 update meeting on Monday, April 15.  Here are the slides: 
[AV1_Layer-specific_OBUs_2024-04-15.pdf](https://github.com/AOMediaCodec/av1-rtp-spec/files/14960418/AV1_Layer-specific_OBUs_2024-04-15.pdf)

**Comment by mhoro** [comment]
Update: at the April 15 meeting mentioned in the comment above, attendees reached consensus that, with small modifications, the RTP spec could be published independently of an AV1 spec update. Consequently, it was decided that there was no rush to make any changes to the AV1 spec.

Caveat: I was unable to attend the April 15 meeting and would appreciate confirmation (and correction if necessary) to the summary above from someone who did attend.

**Comment by mhoro** [comment]
My apologies for the spam.  It appears Bernard's previous message captured the update. 

In the interest of moving forward with the publication of the AV1 for RTP spec, I propose that interested parties meet to craft a plan to identify and draft text for the required RTP spec modifications. I further propose that we coordinate this effort by some means other than git-hib comments (e.g., email). Who would be interested in participating is this meeting/effort?

**Comment by aboba** [comment]
I am interested.On Apr 25, 2024, at 09:26, mhoro ***@***.***> wrote:﻿Re: [AOMediaCodec/av1-rtp-spec] Review of AV1 RTP Payload Specification: Are any changes needed? (Issue #238)My apologies for the spam. It appears Bernard's previous message captured the update.In the interest of moving forward with the publication of the AV1 for RTP spec, I propose that interested parties meet to craft a plan to identify and draft text for the required RTP spec modifications. I further propose that we coordinate this effort by some means other than git-hib comments (e.g., email). Who would be interested in participating is this meeting/effort?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by agrange** [comment]
Review has taken place, and an updated version of the specification has been presented to the working group.
