### ISSUE TITLE
Section 4.4:  Temporal unit mapping into RTP packets

### ISSUE THREAD

**Issue by aboba** [AOMediaCodec/av1-rtp-spec#25]
Section 4.4 contains a note: 

"Add a paragraph that describes how a temporal unit is mapped into RTP packets. I think a new temporal unit should start a new RTP packet. You skip the temporal delimiter OBU, and then packetize the remaining OBUs in one or more packets, with fragmentation as needed."

**Comment by eleft** [comment]
See PR42.

**Comment by aboba** [comment]
I believe this issue is now resolved and should be closed.
