### ISSUE TITLE
Missing Section: SDP parameters

### ISSUE THREAD

**Issue by aboba** [AOMediaCodec/av1-rtp-spec#29]
The specification is missing a section on SDP parameters.  An example can be found in the VP9 payload specification, Section 6.2:
https://tools.ietf.org/html/draft-ietf-payload-vp9-06#page-17

**Comment by eleft** [comment]
We need to address 'tier', offer/answer considerations, IANA registration (incl. contacts).

**Comment by eleft** [comment]
Tier has been addressed. IANA is now a separate issue.

**Comment by aboba** [comment]
I believe this issue is now resolved and should be closed.
