### ISSUE TITLE
IANA registration

### ISSUE THREAD

**Issue by eleft** [AOMediaCodec/av1-rtp-spec#37]

**Comment by eleft** [comment]
Covered in the spec but the actual IANA registration must be performed independently.

**Comment by eleft** [comment]
Reach out to IETF area chairs when we are close to publication.

**Comment by aboba** [comment]
Media Type Registration RFC: https://tools.ietf.org/html/rfc4855

**Comment by StephenBotzko** [comment]
Addressed in PR #193
