### ISSUE TITLE
Consider removing 'no frame aggregation' packetization rule

### ISSUE THREAD

**Issue by eleft** [AOMediaCodec/av1-rtp-spec#47]
Consider deleting the following sentence from the "Packetization Rules" section: 

"With the exception of sequence header and metadata OBUs, an RTP packet MUST contain OBUs associated with a single frame."

**Comment by aboba** [comment]
Is the thinking that this could be allowed as long as the AV1 Descriptor header extension was not negotiated?

**Comment by eleft** [comment]
Agreed to remove.
