### ISSUE TITLE
Simulcast: use of "S" modes

### ISSUE THREAD

**Issue by aboba** [AOMediaCodec/av1-rtp-spec#51]
When simulcast streams are packetized in RTP, what scalability mode is used?  For example, if there are 3 simulcast streams, each with 3 temporal layers, is the "S3T3" scalability mode provided in any (or all?) of the simulcast bitstreams?

**Comment by aboba** [comment]
Discussion at the June 3 meeting: AV1 supports encapsulation of multiple simulcast streams using a single SSRC as well as using a separate SSRC (and RID) for each simulcast stream.  The specification does not currently provide guidance on which of these approaches implementations need to support.

**Comment by eleft** [comment]
Bernard to create initial text.
