### ISSUE TITLE
Layer drop

### ISSUE THREAD

**Issue by aboba** [AOMediaCodec/av1-rtp-spec#52]
How does the RTP encapsulation handle dropping of layers (such as in simulcast)? Is this reflected in a change in the scalability mode (e.g. S3T3 -> S2T3 to signal dropping of a simulcast layer)?

**Comment by eleft** [comment]
The layer drop message should close the loop between the information present in a stream in terms of maximum capabilities (e.g., max frame size in sequence headers, or layers described in the dependency descriptor) and what remains after SFU or other stream filtering.

**Comment by eleft** [comment]
Resolved in 2019/11/04 meeting.
