### ISSUE TITLE
Use of alternative RTP header extensions

### ISSUE THREAD

**Issue by eleft** [AOMediaCodec/av1-rtp-spec#55]
What happens if you use frame marking and not the AV1 dependency descriptor? Is this supported behavior? Frame marking is supported in the Chrome codebase. If we want to support it, we should have text to explain how to use it.

**Comment by agouaillard-cosmo** [comment]
While a legitimate question, I want to point out that a more generic codec-agnostic rtp header is also in chrome, which would be much closer to what AV1 need. (The IPR around frameMarkign at IETF is also not super clear to me.

**Comment by eleft** [comment]
Agreed to say that using frame marking would be problematic, and that the annex descriptor should be used. Bernard to provide text.

**Comment by eleft** [comment]
The existing frame marking draft (currently in 2nd WGLC) does not support AV1, so there is nothing to document here for us.
