### ISSUE TITLE
Discussion of feedback messages in the Annex

### ISSUE THREAD

**Issue by eleft** [AOMediaCodec/av1-rtp-spec#59]

**Comment by eleft** [comment]
If an SFU sends an FIR message, it needs to know what to look for in the annex extension header to know if the constraints are satisfied.

**Comment by aboba** [comment]
FIR text updated in PR https://github.com/AOMediaCodec/av1-rtp-spec/pull/71

**Comment by eleft** [comment]
Current text in A.4.3 covers IDD implementation using Chains.
